### ISSUE TITLE
After device config, The log begins to show these errors. OSX Mojave, Indigo 7.2.

### ISSUE THREAD

**Issue by philippelaurent** [bschollnick/Indigo-UPS-Battery-Plugin#1]
UPS and Battery Monitor Error   plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   UPS and Battery Monitor         	Power Status    - UPS Power
   UPS and Battery Monitor         	UPS Model       -  -Back-UPS BR1000G FW:868.L2 .D USB FW:L2   (id=251396096)
   UPS and Battery Monitor         	Charging Status - False
   UPS and Battery Monitor         	Battery Charge  - 91
   UPS and Battery Monitor         Refreshing in 1 Minutes
   UPS and Battery Monitor Error   Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 217, in runConcurrentThread
ValueError: invalid literal for int() with base 10: '09 remaining pre'

   UPS and Battery Monitor Error   plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by bschollnick** [comment]
What version of Mac OS X do you have running?

Can you please open a terminal and type:

pmset -g batt

And copy and paste the results here?  

I found a different problem, but it doesn't match your results.  

In a nutshell, Apple changed the report results from "pmset -g batt", in 10.7.5 it would report the time remaining even when it was on AC.

For example:
`
Currently drawing from 'AC Power'
 -InternalBattery-0	100%; charged; 0:00 remaining
`

Somewhere between 10.7.5 and 10.13.xx, the results changed to be more dynamic.

On power:
`
nerv:testing tools Benjamin$ pmset -g batt
Now drawing from 'AC Power'
 -UPS CP1000AVRLCD (id=16711680)	100%; charging present: true
`

On battery:

`
Now drawing from 'UPS Power'
 -UPS CP1000AVRLCD (id=16711680)	100%; discharging; 0:22 remaining present: true
`

So if you could cut and paste your results, I'd appreciate it, so that I can compare and see why your results are different from mine...(I can only test v10.7.5 or v10.13.xx currently.)

**Comment by philippelaurent** [comment]
I'm using OSX 10.14.2.

I was able to resolve my specific issue I was having with doing the SMC and
NVRAM resets on the machine this morning.

The results of the pmset -g batt, as requested:

Now drawing from 'AC Power'

 -Back-UPS BR1000G FW:868.L2 .D USB FW:L2   (id=13959168) 100%; charging
present: true


Although my specific issue has apparently been resolved, at least from the
log perspective, I'm happy to do further testing for whatever you need
since I'm on a different OS version than your test platforms.
