### ISSUE TITLE
Release to plugin store?

### ISSUE THREAD

**Issue by FlyingDiver** [bschollnick/Indigo-UPS-Battery-Plugin#3]
You merged the changes but didn't do a store release.  Are you planning on doing so?  Or do you want the store entry to be transferred to me?

**Comment by joshsnelling** [comment]
I still find this plugin useful and I was able to update to a new Indigo version by cloning this repo and installing it manually. Thanks for making those changes @FlyingDiver! Was there a plan on how to move ahead with repo and store ownership for this plugin?

**Comment by FlyingDiver** [comment]
Matt & Jay are trying to get permissions to move this into the Indigo Open Source repo.  The original developer has not been responsive.

**Comment by joshsnelling** [comment]
Understood. Thanks for the quick response and ongoing support!

**Comment by bschollnick** [comment]
I don't understand why I didn't see this original comment?

For some reason, every time I've tried to release this via the Perceptive store, I was unable to do so.  It always had an error.

Since I'm running HomeAssistant (with some annoyances), feel free to do as people wish.

But I've replied to all emails that have been sent to me

**Comment by FlyingDiver** [comment]
If you can add a license file (MIT preferrred) to the repo, then I can (legally) clone and it take it over for Indigo.

**Comment by FlyingDiver** [comment]
If you want, I can do a PR to add the license.

**Comment by bschollnick** [comment]
added

**Comment by FlyingDiver** [comment]
Excellent.  I'll get it added to the open source repo and updated in the store.
